### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by ghost** [xaionaro-go/trezorLuks#5]
```
root@dell:~# `go env GOPATH`/bin/trezorLuks --trezor-key-name myKey luksFormat /dev/loop100
Sent the request to the Trezor device (please confirm the operation if required)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x60ed39]

goroutine 1 [running]:
github.com/xaionaro-go/cryptoWallet/internal/wallets/satoshilabs/trezor.(*TrezorBase).CheckConnection(0xc0000d6600, 0xc0000e5d08, 0xc0000e5d30)
	/root/go/src/github.com/xaionaro-go/cryptoWallet/internal/wallets/satoshilabs/trezor/trezor.go:121 +0x29
github.com/xaionaro-go/cryptoWallet/internal/wallets/satoshilabs/trezor.(*TrezorBase).DecryptKey(0xc0000d6600, 0x6b691b, 0xb, 0x8f6020, 0x20, 0x20, 0x8f57b0, 0x10, 0x10, 0x7ffd5a0e980d, ...)
	/root/go/src/github.com/xaionaro-go/cryptoWallet/internal/wallets/satoshilabs/trezor/trezor.go:183 +0x43
main.main()
	/root/go/src/github.com/xaionaro-go/trezorLuks/main.go:90 +0x3b5

```
```
root@dell:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.10
DISTRIB_CODENAME=eoan
DISTRIB_DESCRIPTION="Ubuntu 19.10"

```

**Comment by xaionaro** [comment]
@qwertyx64 : could you also copy&paste here the output of `lsusb` (or just the line with your Trezor device)?
